<?php
if( function_exists('acf_add_local_field_group') ):

// acf_add_local_field_group(array (
// 	'key' => 'group_56cbac453acf3',
// 	'title' => 'Amazon SES Email',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_56cbac4a15c80',
// 			'label' => 'Send via Amazon',
// 			'name' => 'msw_ses_send_via_amazon',
// 			'type' => 'true_false',
// 			'instructions' => 'May be unreliable on third-party, non-Makespace hosting',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'message' => 'Yes, send emails from this site using Amazon SES',
// 			'default_value' => 1,
// 		),
// 		array (
// 			'key' => 'field_56e221da427ab',
// 			'label' => 'Sender Name',
// 			'name' => 'msw_ses_sender_name',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => 'WordPress',
// 			'placeholder' => 'WordPress',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_56cbadc4102fe',
// 			'label' => 'Sender Email',
// 			'name' => 'msw_ses_sender_email',
// 			'type' => 'email',
// 			'instructions' => 'If using a different email address, it must first be validated on Amazon',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => 'wp@makespaceweb.com',
// 			'placeholder' => 'wp@makespaceweb.com',
// 			'prepend' => '',
// 			'append' => '',
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'options_page',
// 				'operator' => '==',
// 				'value' => 'msw-framework-options',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'side',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => 'Enables sending via Makespace\'s Amazon SES email',
// 	'local' => 'php',
// ));

// acf_add_local_field_group(array (
// 	'key' => 'group_57baf550b8fda',
// 	'title' => 'Google Maps',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_57baf557b0230',
// 			'label' => 'API Key',
// 			'name' => 'msw_google_map_api_key',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'options_page',
// 				'operator' => '==',
// 				'value' => 'msw-framework-options',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'side',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => 'Enables sending via Makespace\'s Amazon SES email',
// 	'local' => 'php',
// ));

// acf_add_local_field_group(array (
// 	'key' => 'group_56c5356f1e6e2',
// 	'title' => 'Theme Options',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_56c53575b5a60',
// 			'label' => 'Site Logo',
// 			'name' => 'site_logo',
// 			'type' => 'image',
// 			'instructions' => 'site_logo',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => 40,
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'return_format' => 'url',
// 			'preview_size' => 'medium',
// 			'library' => 'all',
// 			'min_width' => '',
// 			'min_height' => '',
// 			'min_size' => '',
// 			'max_width' => '',
// 			'max_height' => '',
// 			'max_size' => '',
// 			'mime_types' => '',
// 		),
// 		array (
// 			'key' => 'field_56c53593b5a61',
// 			'label' => 'Favicon',
// 			'name' => 'favicon',
// 			'type' => 'image',
// 			'instructions' => 'favicon',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '30',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'return_format' => 'url',
// 			'preview_size' => 'medium',
// 			'library' => 'all',
// 			'min_width' => '',
// 			'min_height' => '',
// 			'min_size' => '',
// 			'max_width' => '',
// 			'max_height' => '',
// 			'max_size' => '',
// 			'mime_types' => '',
// 		),
// 		array (
// 			'key' => 'field_56c7ebe15394e',
// 			'label' => 'Menu Type',
// 			'name' => 'menu_type',
// 			'type' => 'select',
// 			'instructions' => 'menu_type',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '30',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'choices' => array (
// 				'ocn' => 'Off Canvas',
// 				'dropdown' => 'Dropdown',
// 				'custom' => 'Custom',
// 			),
// 			'default_value' => array (
// 				0 => 'ocn',
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'ui' => 0,
// 			'ajax' => 0,
// 			'return_format' => 'value',
// 			'placeholder' => '',
// 		),
// 		array (
// 			'key' => 'field_56c53a165ed97',
// 			'label' => 'Contact Information',
// 			'name' => 'contact_information',
// 			'type' => 'repeater',
// 			'instructions' => 'contact_information',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'collapsed' => 'field_56c7e20b24c5a',
// 			'min' => '',
// 			'max' => '',
// 			'layout' => 'block',
// 			'button_label' => 'Add Contact Information',
// 			'sub_fields' => array (
// 				array (
// 					'key' => 'field_56c53a895ed99',
// 					'label' => 'Map',
// 					'name' => 'map',
// 					'type' => 'google_map',
// 					'instructions' => 'map',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 50,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'center_lat' => '',
// 					'center_lng' => '',
// 					'zoom' => '',
// 					'height' => 150,
// 				),
// 				array (
// 					'key' => 'field_56c7e13924c55',
// 					'label' => 'Address',
// 					'name' => 'address',
// 					'type' => 'textarea',
// 					'instructions' => 'address',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 30,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'maxlength' => '',
// 					'rows' => 9,
// 					'new_lines' => 'br',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_56c8795c3d137',
// 					'label' => 'Map Marker',
// 					'name' => 'map_marker',
// 					'type' => 'image',
// 					'instructions' => 'map_marker',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 20,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'return_format' => 'url',
// 					'preview_size' => 'thumbnail',
// 					'library' => 'all',
// 					'min_width' => '',
// 					'min_height' => '',
// 					'min_size' => '',
// 					'max_width' => '',
// 					'max_height' => '',
// 					'max_size' => '',
// 					'mime_types' => '',
// 				),
// 				array (
// 					'key' => 'field_56c7e20b24c5a',
// 					'label' => 'Location Name',
// 					'name' => 'location_name',
// 					'type' => 'text',
// 					'instructions' => 'location_name',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 25,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_56c7e1b924c57',
// 					'label' => 'Phone Number',
// 					'name' => 'phone_number',
// 					'type' => 'text',
// 					'instructions' => 'phone_number',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 25,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_56c7e1dd24c59',
// 					'label' => 'Email Address',
// 					'name' => 'email_address',
// 					'type' => 'email',
// 					'instructions' => 'email_address',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 25,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 				),
// 				array (
// 					'key' => 'field_56c7e1cd24c58',
// 					'label' => 'Fax Number',
// 					'name' => 'fax_number',
// 					'type' => 'text',
// 					'instructions' => 'fax_number',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 25,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_56c87a7c702e0',
// 					'label' => 'Social Media Links',
// 					'name' => 'social_media_links',
// 					'type' => 'repeater',
// 					'instructions' => 'social_media_links',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'collapsed' => '',
// 					'min' => '',
// 					'max' => '',
// 					'layout' => 'table',
// 					'button_label' => 'Add Site',
// 					'sub_fields' => array (
// 						array (
// 							'key' => 'field_56c87a89702e1',
// 							'label' => 'Site',
// 							'name' => 'site',
// 							'type' => 'text',
// 							'instructions' => 'site',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '33',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => 'eg, Facebook',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 						array (
// 							'key' => 'field_56c87a97702e2',
// 							'label' => 'URL',
// 							'name' => 'url',
// 							'type' => 'text',
// 							'instructions' => 'url',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '34',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => 'eg, https://www.facebook.com/company',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 						array (
// 							'key' => 'field_57bb0a976cbb8',
// 							'label' => 'Class',
// 							'name' => 'class',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '33',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 						),
// 					),
// 				),
// 			),
// 		),
// 		array (
// 			'key' => 'field_56c535d1f0ce4',
// 			'label' => 'Header JavaScript',
// 			'name' => 'header_javascript',
// 			'type' => 'textarea',
// 			'instructions' => 'Insert your Google Analytics, Visistat, or other header JavaScript here. Be sure to include the script tags as needed.',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => 50,
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'maxlength' => '',
// 			'rows' => 8,
// 			'new_lines' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_56c53b93f1877',
// 			'label' => 'Footer JavaScript',
// 			'name' => 'footer_javascript',
// 			'type' => 'textarea',
// 			'instructions' => 'Enter any retargeting or other JavaScript to be included before the closing <em>body</em> tag.',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => 50,
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'maxlength' => '',
// 			'rows' => 8,
// 			'new_lines' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'options_page',
// 				'operator' => '==',
// 				'value' => 'msw-framework-options',
// 			),
// 		),
// 	),
// 	'menu_order' => 10,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => 'General Theme Options',
// ));

// acf_add_local_field_group(array (
// 	'key' => 'group_56c54930c0959',
// 	'title' => 'Custom Post Types',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_56c7f59ce0fcb',
// 			'label' => 'Instructions',
// 			'name' => '',
// 			'type' => 'message',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'message' => 'Create custom post types to be used in this theme.',
// 			'new_lines' => 'wpautop',
// 			'esc_html' => 0,
// 		),
// 		array (
// 			'key' => 'field_56c54957ae42a',
// 			'label' => 'Post Type',
// 			'name' => 'msw_post_type',
// 			'type' => 'repeater',
// 			'instructions' => 'msw_post_type',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'collapsed' => 'field_56c5498aae42c',
// 			'min' => '',
// 			'max' => '',
// 			'layout' => 'block',
// 			'button_label' => 'Add Post Type',
// 			'sub_fields' => array (
// 				array (
// 					'key' => 'field_56c5498aae42c',
// 					'label' => 'Plural Name',
// 					'name' => 'plural_name',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 1,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 33,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_56c5497aae42b',
// 					'label' => 'Singular Name',
// 					'name' => 'singular_name',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 1,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 33,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_56c54a1467543',
// 					'label' => 'Slug',
// 					'name' => 'slug',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 1,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 34,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_56c54a9667544',
// 					'label' => 'Dashicon',
// 					'name' => 'dashicon',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 33,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => 'dashicons-admin-generic',
// 					'placeholder' => 'dashicons-admin-generic',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_56c54cf3c6d10',
// 					'label' => 'Menu Position',
// 					'name' => 'menu_position',
// 					'type' => 'select',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 33,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'choices' => array (
// 						5 => 'Below Posts',
// 						10 => 'Below Media',
// 						20 => 'Below Pages',
// 						25 => 'Below Comments',
// 						60 => 'Below 1st Separator',
// 						65 => 'Below Plugins',
// 						70 => 'Below Users',
// 						75 => 'Below Tools',
// 						80 => 'Below Settings',
// 						100 => 'Below 2nd Separator',
// 					),
// 					'default_value' => array (
// 						0 => 5,
// 					),
// 					'allow_null' => 0,
// 					'multiple' => 0,
// 					'ui' => 0,
// 					'ajax' => 0,
// 					'placeholder' => '',
// 					'disabled' => 0,
// 					'readonly' => 0,
// 					'return_format' => 'value',
// 				),
// 				array (
// 					'key' => 'field_56e2260b0fc86',
// 					'label' => 'Menu Name',
// 					'name' => 'menu_name',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 34,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_56c54ac44d70c',
// 					'label' => 'Options (supports)',
// 					'name' => 'options_supports',
// 					'type' => 'checkbox',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'choices' => array (
// 						'title' => 'Title',
// 						'editor' => 'WYSIWYG Editor',
// 						'thumbnail' => 'Featured Image',
// 						'excerpt' => 'Excerpt',
// 						'page-attributes' => 'Page Attributes',
// 					),
// 					'default_value' => array (
// 						0 => 'title',
// 						1 => 'editor',
// 						2 => 'thumbnail',
// 						3 => 'page-attributes',
// 					),
// 					'layout' => 'horizontal',
// 					'toggle' => 0,
// 					'return_format' => 'value',
// 				),
// 				array (
// 					'key' => 'field_56c54bd4c6d0f',
// 					'label' => 'Public Information',
// 					'name' => 'public_information',
// 					'type' => 'checkbox',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => 50,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'choices' => array (
// 						'has_archive' => 'Has Archive Page',
// 						'exclude_from_search' => 'Exclude from Searches',
// 					),
// 					'default_value' => array (
// 						0 => 0,
// 					),
// 					'layout' => 'vertical',
// 					'toggle' => 0,
// 					'return_format' => 'value',
// 				),
// 				array (
// 					'key' => 'field_56e2310fcf577',
// 					'label' => 'Breadcrumb Parent',
// 					'name' => 'breadcrumb_parent',
// 					'type' => 'post_object',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => array (
// 						array (
// 							array (
// 								'field' => 'field_56c54bd4c6d0f',
// 								'operator' => '!=',
// 								'value' => 'has_archive',
// 							),
// 						),
// 					),
// 					'wrapper' => array (
// 						'width' => 50,
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'post_type' => array (
// 						0 => 'page',
// 					),
// 					'taxonomy' => array (
// 					),
// 					'allow_null' => 0,
// 					'multiple' => 0,
// 					'return_format' => 'object',
// 					'ui' => 1,
// 				),
// 				array (
// 					'key' => 'field_56c54d8780da9',
// 					'label' => 'Taxonomies',
// 					'name' => 'taxonomies',
// 					'type' => 'repeater',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'collapsed' => '',
// 					'min' => '',
// 					'max' => '',
// 					'layout' => 'table',
// 					'button_label' => 'Add Row',
// 					'sub_fields' => array (
// 						array (
// 							'key' => 'field_56c54d9380daa',
// 							'label' => 'Plural Name',
// 							'name' => 'plural_name',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 1,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => 25,
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_56c54df580dab',
// 							'label' => 'Singular Name',
// 							'name' => 'singular_name',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 1,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => 25,
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_56c54e1080dac',
// 							'label' => 'Slug',
// 							'name' => 'slug',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 1,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => 25,
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_56c54e1f80dad',
// 							'label' => 'Type',
// 							'name' => 'type',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 1,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => 25,
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'yes' => 'Like Categories',
// 								'no' => 'Like Tags',
// 							),
// 							'default_value' => array (
// 								0 => 'yes',
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 							'return_format' => 'value',
// 						),
// 					),
// 				),
// 			),
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'options_page',
// 				'operator' => '==',
// 				'value' => 'msw-framework-post-types',
// 			),
// 		),
// 	),
// 	'menu_order' => 20,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => 'Create custom post types for this site',
// 	'local' => 'php',
// ));

/*
acf_add_local_field_group(array (
	'key' => 'group_56c7e7de46cf1',
	'title' => 'MailChimp Configuration',
	'fields' => array (
		array (
			'key' => 'field_56c7e86a2f7cc',
			'label' => 'Fields',
			'name' => 'mailchimp_fields',
			'type' => 'repeater',
			'instructions' => 'mailchimp_fields',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_56c7e8802f7cd',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Field',
			'sub_fields' => array (
				array (
					'key' => 'field_56c7e8802f7cd',
					'label' => 'Label',
					'name' => 'label',
					'type' => 'text',
					'instructions' => 'label',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'eg, Email Address',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56c7e89b2f7ce',
					'label' => 'Field Name',
					'name' => 'field_name',
					'type' => 'text',
					'instructions' => 'field_name',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'eg, EMAIL',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_56c7e8ea2f7cf',
			'label' => 'Button Text',
			'name' => 'mailchimp_button_text',
			'type' => 'text',
			'instructions' => 'mailchimp_button_text',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Join',
			'placeholder' => 'Join',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c7e9162f7d0',
			'label' => 'Confirmation Message',
			'name' => 'mailchimp_confirmation_message',
			'type' => 'text',
			'instructions' => 'mailchimp_confirmation_message',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Thank you for subscribing',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c7e7e62f7ca',
			'label' => 'API Key',
			'name' => 'mailchimp_api_key',
			'type' => 'text',
			'instructions' => 'mailchimp_api_key',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56c7e8612f7cb',
			'label' => 'List ID',
			'name' => 'mailchimp_list_id',
			'type' => 'text',
			'instructions' => 'mailchimp_list_id',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'msw-framework-options',
			),
		),
	),
	'menu_order' => 100,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Configure MailChimp form and API',
	'local' => 'php',
));

acf_add_local_field_group(array (
	'key' => 'group_56c7f5f254d0f',
	'title' => 'Hooks & Functions',
	'fields' => array (
		array (
			'key' => 'field_56c7f6034f146',
			'label' => 'Add links to the sitemap generated on the sitemap page',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '<pre>function add_to_sitemap( $sitemap ){
	$sitemap .= \'&lt;li&gt;&lt;a href="#"&gt;Custom link!&lt;/a&gt;&lt;/li&gt;\';
	return $sitemap;
}
apply_filters( \'msw_add_to_sitemap\', \'add_to_sitemap\' );</pre>',
			'new_lines' => '',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56e22786f41fa',
			'label' => 'Generate a Google map',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Add <code>&lt;div id="gmap"&gt;&lt;/div&gt;</code> to the site to automatically generate a Google map with the locations and markers set in the options. You must set a height for this div in order for the map to appear.',
			'new_lines' => '',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56e228cd53e92',
			'label' => 'Add a Mailchimp form',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Use <code>mailchimp_form();</code> to create a Mailchimp form with the fields you set in the options.',
			'new_lines' => '',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56e25033f34b5',
			'label' => 'Nav Toggle',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'If using the built-in dropdown or off canvas navigation menu, any item with the <code>.nav-toggle</code> class will toggle the menu open or closed.',
			'new_lines' => '',
			'esc_html' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'msw-framework-documentation',
			),
		),
	),
	'menu_order' => 200,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Documentation for hooks and functions',
));
*/
endif;